### ISSUE TITLE
pusher_1.default is not a constructor

### ISSUE THREAD

**Issue by gulsharan** [underfisk/nestjs-pusher#1]
@underfisk Thanks for creating this amazing library! However, I noticed the following error as I tried using it in one of my projects. On some digging, I found that the issue gets fixed if you use `import * as Pusher` instead of `import Pusher` in [this line](https://github.com/underfisk/nestjs-pusher/blob/b04c8614ded335c3af07fff0ebd0962e0a8b3aba/src/pusher.service.ts#L2). Please let me know if you need a PR for this change.

```javascript
node_modules/nestjs-pusher/dist/pusher.service.js:21
        this.pusher = new pusher_1.default(options);
^
TypeError: pusher_1.default is not a constructor
    at new PusherService (/Users/gul/Dev/vt_ed/dist/apps/api/webpack:/vt/node_modules/nestjs-pusher/dist/pusher.service.js:21:1)
```

**Comment by underfisk** [comment]
@gulsharan Thanks for reporting this, if you could do a PR that would be great

**Comment by gulsharan** [comment]
Wow, you are quick! Sure, will send you a PR shortly. :)

**Comment by underfisk** [comment]
@gulsharan v0.0.5 is now available in NPM

**Comment by gulsharan** [comment]
@underfisk Looks like the new package does not have any files.
<img width="151" alt="image" src="https://user-images.githubusercontent.com/577631/157763961-d4ba7163-e931-4d87-856f-6d137f9c6e52.png">

**Comment by underfisk** [comment]
> @underfisk Looks like the new package does not have any files. <img alt="image" width="151" src="https://user-images.githubusercontent.com/577631/157763961-d4ba7163-e931-4d87-856f-6d137f9c6e52.png">

Thanks for reporting, indeed something went wrong but i'll take a quick look

**Comment by underfisk** [comment]
@gulsharan Okay so i did release v0.0.6 that contains also a fix for the new pusher version, could you check if everything is alright in your project?

**Comment by gulsharan** [comment]
I tried again from scratch, but it installed `pusher` version `^4.0.2` by default. I believe you need to update the following line in package.json
https://github.com/underfisk/nestjs-pusher/blob/df7350c15f4d853531ed61819dd0bccf5f7602c0/package.json#L83

The original issue is resolved btw.

**Comment by underfisk** [comment]
> I tried again from scratch, but it installed `pusher` version `^4.0.2` by default. I believe you need to update the following line in package.json
> 
> https://github.com/underfisk/nestjs-pusher/blob/df7350c15f4d853531ed61819dd0bccf5f7602c0/package.json#L83
> 
> The original issue is resolved btw.

You're right, i haven't noticed that i did just upgrade the dev dependency, i'm going to release 0.0.7 (i'm sorry for the mess) but it has been a while that i haven't released a new version

**Comment by gulsharan** [comment]
> (i'm sorry for the mess) but it has been a while that i haven't released a new version

No problem at all. I am just thankful for all your help and such your quick response.

**Comment by gulsharan** [comment]
It works now. I will test other features of the library in coming days, and will keep you posted if I see any area of improvement. Thanks for all the help!
