### ISSUE TITLE
Missing `@UseInterceptor` decorator in documentation

### ISSUE THREAD

**Issue by futurus** [underfisk/nestjs-pusher#16]
Per https://docs.nestjs.com/interceptors#binding-interceptors

**Comment by underfisk** [comment]
@futurus Hey there, thanks for pointing this out. Is there any change proposal?
I haven't touched on the project for a while but I've been actively accepting contributions and updating dependencies, if you're able to perform the change that's missing I'll be happy to review

**Comment by underfisk** [comment]
I'm closing to close this issue but for anyone looking for binding interceptors just remember that this library provides its own interceptors but you can bind as much as you want since a controller is a normal Nestjs controller. (pipes, guards, interceptors etc)
