### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by pishguy** [underfisk/nestjs-pusher#18]
Is there any sample code to know how can we use and sent event to Pusher?

**Comment by underfisk** [comment]
@pishguy Hi, are you looking for samples from the server to client or client to server?

From the server to the client you have a few options:
- Bind the decorator to your controller with the event name/options and it will send to the client
- You can inject the pusher client and use it by yourself to send (e.g: in your service/controller constructor add `private readonly pusherService: PusherService` and it should inject). Here's an example

If you wish to send from the client to the server, the official pusherjs examples will work as this library is agnostic to its client but there's an example section if you want to use chunking: `https://underfisk.github.io/nestjs-pusher/docs/client-side`

I might have to update the documentation as it seems outdated but let me know if this helped you

**Comment by pishguy** [comment]
@underfisk 

thanks so much, i have another questions:
1) how can i trigger to channel or channel and event without using decorators? for example triggering to channel into EmailService such as this code:

```js
await this.pusher.trigger(channel, event, data);
```

2) could you take us sample code of service? what's the triggering function, i can't found out in documented site

**Comment by underfisk** [comment]
> @underfisk
> 
> thanks so much, i have another questions:
> 
> 1. how can i trigger to channel or channel and event without using decorators? for example triggering to channel into EmailService such as this code:
> 
> ```js
> await this.pusher.trigger(channel, event, data);
> ```
> 
> 2. could you take us sample code of service? what's the triggering function, i can't found out in documented site

The decorators are optional, you can use the `PusherService` that has the trigger functionality for you. That all you need to do is ask for `PusherService` token in your `EmailService` constructor
I will have to update the documentation soon as i know some pieces are missing, here's an example based on your request

```typescript

class EmailService {
    constructor(private readonly pusherService: PusherService, private readonly yourOtherService: MyOtherService){}

   public async sendMyEmailAndNotifyPusher(){
     this.whateverYouNeedToPerform()
     await this.pusherService.trigger(channelName, eventName, data, socketId)
   }
}
```

Although if the service doesn't satisfy your needs and you actually want the underlying pusher instance, you can access using `pusherService.getPusherInstance()`

If you need to see how I'm using the service, here's the interceptor implementation: https://github.com/underfisk/nestjs-pusher/blob/master/src/pusher.interceptor.ts
